name: Marissa Traina
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/js
